-- ==========================================================================
-- Module 3 — Payment & Delivery Tracking (Imtiaj).  SDD §5.4.4 ERDs.
-- Loaded after schema.sql (see spring.sql.init.schema-locations), so the
-- orders table already exists for the foreign keys below.
-- ==========================================================================

DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS transaction;
DROP TABLE IF EXISTS driver;

-- TRANSACTION (SDD 5.4.4). No card data stored (PCI) — only the gateway ref.
CREATE TABLE transaction (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT REFERENCES orders(order_id),
    gateway_ref    VARCHAR(120),
    amount         DECIMAL(10,2),
    currency       CHAR(3) DEFAULT 'MYR',
    status         VARCHAR(10),
    paid_at        TIMESTAMP
);

-- DRIVER (SDD 5.4.4). is_active = eligible for dispatch.
CREATE TABLE driver (
    driver_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120),
    phone      VARCHAR(20),
    vehicle    VARCHAR(60),
    is_active  BOOLEAN DEFAULT TRUE
);

-- DELIVERY (SDD 5.4.4). Live GPS pushed via WebSocket (DT-M3-2).
CREATE TABLE delivery (
    delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT REFERENCES orders(order_id),
    driver_id   BIGINT REFERENCES driver(driver_id),
    status      VARCHAR(20) DEFAULT 'PREPARING',
    current_lat DECIMAL(9,6),
    current_lng DECIMAL(9,6),
    eta         TIMESTAMP
);
