-- ==========================================================================
-- Online Food Delivery System — schema (SDD §5.4 Information Viewpoint / ERDs)
-- Module 1 tables: app_user, session, restaurant, menu_item.
-- Portable DDL: runs on PostgreSQL (default profile) and H2 in PostgreSQL mode
-- (local profile). Recreated on each boot for a deterministic demo DB.
-- ==========================================================================

DROP TABLE IF EXISTS cart_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS menu_item;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS restaurant;
DROP TABLE IF EXISTS app_user;

-- USER (SDD 5.4.2). failed_attempts + locked_until added to realise DT-M1-1
-- R4/R5 (increment on wrong password; lock the account for 15 minutes).
CREATE TABLE app_user (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(120),
    email          VARCHAR(160) UNIQUE NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    phone          VARCHAR(20),
    role           VARCHAR(10)  NOT NULL CHECK (role IN ('CUSTOMER','ADMIN','DRIVER')),
    failed_attempts INT         NOT NULL DEFAULT 0,
    locked_until   TIMESTAMP,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- SESSION (SDD 5.4.2) — issued JWT audit trail (requests stay stateless).
CREATE TABLE session (
    session_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT REFERENCES app_user(user_id),
    jwt_token   VARCHAR(512),
    issued_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at  TIMESTAMP
);

-- RESTAURANT (SDD 5.4.2). is_open drives the 'Currently Closed' badge (DT-M1-3).
CREATE TABLE restaurant (
    restaurant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150),
    cuisine       VARCHAR(60),
    rating        DECIMAL(2,1),
    location      VARCHAR(255),
    is_open       BOOLEAN DEFAULT TRUE
);

-- MENU_ITEM (SDD 5.4.2) — composition under RESTAURANT.
CREATE TABLE menu_item (
    menu_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES restaurant(restaurant_id),
    name          VARCHAR(150),
    description   VARCHAR(1000),
    price         DECIMAL(10,2),
    is_available  BOOLEAN DEFAULT TRUE
);

-- ===================== Module 2 — Cart & Order (Anas) =====================

-- CART (SDD 5.4.3). status ACTIVE -> CONVERTED after checkout.
CREATE TABLE cart (
    cart_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES app_user(user_id),
    status     VARCHAR(12) DEFAULT 'ACTIVE',
    subtotal   DECIMAL(10,2) DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CART_ITEM (SDD 5.4.3). quantity validated 1..20 (DT-M2-1).
CREATE TABLE cart_item (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id      BIGINT REFERENCES cart(cart_id),
    menu_item_id BIGINT REFERENCES menu_item(menu_item_id),
    quantity     INT,
    unit_price   DECIMAL(10,2)
);

-- ORDERS (SDD 5.4.3). status lifecycle enforced by the State pattern (SDD 5.8.5).
CREATE TABLE orders (
    order_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT REFERENCES app_user(user_id),
    cart_id          BIGINT REFERENCES cart(cart_id),
    delivery_address VARCHAR(255),
    total_amount     DECIMAL(10,2),
    status           VARCHAR(20) DEFAULT 'PENDING_PAYMENT',
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
